---
title: "VAXES"
author: "Filip Yaghob"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(data.table)
library(lubridate)
```

```{r function_read_plus}
read_plus <- function(flnm)
{
  read_csv(flnm, col_types = cols(.default = "c")) %>% 
    mutate(filename = flnm,
           data_year = substr(filename, 8, 11))
}
```

``` {r load_data}
vaxes <-
  list.files(pattern = "*VAERSVAX.csv",
             path = "./data/",
             full.names = T) %>% 
  map_df(~read_plus(.))

main_data <-
  list.files(pattern = "*VAERSDATA.csv",
             path = "./data/",
             full.names = T) %>% 
  map_df(~read_plus(.))
```

```{r change_datatypes}
main_data$RECVDATE = mdy(main_data$RECVDATE)
main_data$AGE_YRS = as.factor(main_data$AGE_YRS)
main_data$VAX_DATE = mdy(main_data$VAX_DATE)
main_data$data_year = as.factor(main_data$data_year)

#symptomps$data_year = as.factor(symptomps$data_year)
```

```{r merge_vax_to_data}
big_data <- vaxes %>%
  merge(main_data, by="VAERS_ID", all.x = T) %>%
  select(VAERS_ID, RECVDATE, AGE_YRS, SEX, SYMPTOM_TEXT, DIED, VAX_DATE, NUMDAYS, LAB_DATA,
         VAX_TYPE, VAX_MANU, VAX_LOT, VAX_DOSE_SERIES, VAX_NAME,
         data_year.y) %>%
  rename(DATA_YEAR = data_year.y) %>%
  mutate(VAX_YEAR = year(RECVDATE))
```

```{r typy_vakcin}
types <- vaxes %>%
  group_by(VAX_TYPE) %>%
  summarise(countof = n(), .groups="keep")
```

```{r compute_groups, echo=FALSE, warning=FALSE}
groups <- big_data %>%
  group_by(VAX_YEAR, VAX_TYPE, VAX_MANU) %>%
  summarise(countof = n())
```

```{r groups_per_years}
gpy <- groups %>%
  group_by(VAX_YEAR) %>%
  summarise(countof = sum(countof))
```

```{r export_big_data}
write.table(head(big_data), "bigdata.csv", quote = F, sep = ';', na = "NA", row.names = F, dec=',')

```
